prometheus:
  prometheusSpec:
    retention: 30d
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi

grafana:
  persistence:
    enabled: true
    size: 10Gi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
  dashboards:
    default:
      system-metrics:
        file: dashboards/system-metrics.json
      application-metrics:
        file: dashboards/application-metrics.json
      business-metrics:
        file: dashboards/business-metrics.json

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'email'
      routes:
      - match:
          severity: critical
        receiver: 'slack'
    receivers:
    - name: 'email'
      email_configs:
      - to: 'alerts@learning-atomizer.com'
        from: 'prometheus@learning-atomizer.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'alerts@learning-atomizer.com'
        auth_password: '${SMTP_PASSWORD}'
    - name: 'slack'
      slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
