version: '1.0'

# Global Configuration
global:
  environment: production
  version: 1.0.0
  region: us-east-1
  domain: learning-atomizer.com

# Infrastructure Configuration
infrastructure:
  aws:
    regions:
      - us-east-1
      - eu-west-1
      - ap-southeast-1
    services:
      - ec2
      - rds
      - elasticache
      - s3
      - cloudfront
      - route53
      - acm
  
  kubernetes:
    version: 1.24
    clusters:
      - name: primary-cluster
        region: us-east-1
        nodes:
          min: 3
          max: 10
          type: t3.large
      - name: secondary-cluster
        region: eu-west-1
        nodes:
          min: 2
          max: 8
          type: t3.large

# Application Configuration
application:
  server:
    replicas:
      min: 3
      max: 10
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 70
        - type: memory
          target: 80
  
  client:
    replicas: 3
    resources:
      requests:
        cpu: 0.5
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

# Database Configuration
databases:
  mongodb:
    version: 5.0
    replicas: 3
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 4
        memory: 8Gi
    backup:
      enabled: true
      schedule: "0 2 * * *"
      retention: 30d
  
  redis:
    version: 6.2
    replicas: 3
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi

# Storage Configuration
storage:
  s3:
    buckets:
      - name: content-storage
        versioning: enabled
        encryption: AES256
      - name: backup-storage
        versioning: enabled
        encryption: AES256
        lifecycle:
          enabled: true
          expiration: 90d

# Networking Configuration
networking:
  vpc:
    cidr: 10.0.0.0/16
    subnets:
      public:
        - 10.0.1.0/24
        - 10.0.2.0/24
      private:
        - 10.0.10.0/24
        - 10.0.11.0/24
  
  security:
    ssl: true
    waf: enabled
    ddos_protection: enabled

# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    retention: 30d
    resources:
      requests:
        cpu: 1
        memory: 2Gi
  
  grafana:
    enabled: true
    persistence: true
    dashboards:
      - system-metrics
      - application-metrics
      - business-metrics
  
  alerts:
    endpoints:
      - type: email
        address: alerts@learning-atomizer.com
      - type: slack
        webhook: https://hooks.slack.com/services/xxx
    rules:
      - name: high-cpu
        threshold: 85
        duration: 5m
      - name: high-memory
        threshold: 85
        duration: 5m
      - name: high-latency
        threshold: 1000ms
        duration: 5m

# Logging Configuration
logging:
  elasticsearch:
    enabled: true
    retention: 30d
    resources:
      requests:
        cpu: 2
        memory: 4Gi
  
  kibana:
    enabled: true
    resources:
      requests:
        cpu: 1
        memory: 2Gi
  
  fluentd:
    enabled: true
    resources:
      requests:
        cpu: 0.5
        memory: 1Gi

# Backup Configuration
backup:
  enabled: true
  schedule: "0 1 * * *"
  retention: 30d
  destinations:
    - type: s3
      bucket: backup-storage
    - type: glacier
      vault: long-term-backup

# Security Configuration
security:
  authentication:
    jwt:
      expiry: 24h
      refresh_expiry: 7d
    oauth:
      providers:
        - google
        - microsoft
  
  encryption:
    at_rest: true
    in_transit: true
    key_rotation: 90d
  
  compliance:
    gdpr: enabled
    hipaa: enabled
    audit_logging: enabled

# Performance Configuration
performance:
  cdn:
    enabled: true
    providers:
      - cloudfront
  
  caching:
    redis:
      maxmemory: 4gb
      policy: allkeys-lru
  
  optimization:
    compression: enabled
    minification: enabled
    image_optimization: enabled

# Disaster Recovery Configuration
disaster_recovery:
  rpo: 1h
  rto: 4h
  backup_regions:
    - eu-west-1
    - ap-southeast-1
  failover:
    automatic: true
    threshold: 5m
