apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-atomizer-server
  namespace: learning-atomizer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: learning-atomizer-server
  template:
    metadata:
      labels:
        app: learning-atomizer-server
    spec:
      containers:
      - name: server
        image: [ECR_URL]/learning-atomizer-server:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: uri
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: host
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ecr-secret
