apiVersion: v1
kind: Service
metadata:
  name: learning-atomizer-server
  namespace: learning-atomizer
spec:
  selector:
    app: learning-atomizer-server
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: learning-atomizer-client
  namespace: learning-atomizer
spec:
  selector:
    app: learning-atomizer-client
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
